### ISSUE TITLE
Shop Stock Replenishes Immediately on Exit

### ISSUE THREAD

**Issue by Suitecake** [ValyriaTear/ValyriaTear#298]
The shop stock in Flora's Boutique (only tested in Flora's Boutique) replenishes if the shop screen is closed then re-opened.

To observe, buy all Minor Healing Potions (10 total), such that it's removed from the list. Close the shop screen, then immediately talk to Flora again. Flora's stock has fully replenished.

**Comment by Suitecake** [comment]
Have you done any initial work on this task, Bertram? If not, I'd be up for working on this.

**Comment by Bertram25** [comment]
Nope, the initial work done was to try and give specs in the summary after looking closely at the current code. :) Have a go as you see fit.

**Comment by Bertram25** [comment]
@Suitecake As I've almost finished with refactoring the targeting code. (That one was nasty. ;]) I'll take this one now.
