### ISSUE TITLE
Split the translation catalog into several .pot files

### ISSUE THREAD

**Issue by akien-mga** [ValyriaTear/ValyriaTear#341]
The current translation catalog for Episode I has everything included in a single .pot file.
Since the project is now using Transifex which has a nice layout, it would make sense to split this big .pot file into several thematic .pot files:

- [x] Source code. (src/)
- [x] Boot sequence (data/boot_menu)
- [x] Inventory items translations (data/inventory)
- [x] Entities (characters/enemies) translations (data/entities)
- [x] Skills (data/skills)
- [x] Config (data/config)
Story per episode:
- [x] ~Common parts (data/story/common)~
- [x] Episode I (data/story/episode1)
... and so on
Would actually be cool to have a system that does a po per data/story sub-folder
- [x] intro/ending (data/story scripts) intro will have to be moved into episode1, ending into common/ for now.

**Comment by bmorel** [comment]
Nice. Considering that I have still not found how to beat Andromalius, how could I translate the strings without spoiling myself?

**Comment by Bertram25** [comment]
> Nice. Considering that I have still not found how to beat Andromalius, how could I translate the strings without spoiling myself?

Eh eh. :) I'm not sure I completely get what's behind the question but if you simply want to take part of the translation effort. You can create a transifex account and ask to join the Valyria tear project.

Otherwise, you can get poedit. And open the po files available in the po/ folder.

If you have other questions, don't hesitate to open an issue or a topic on the forums. :)

**Comment by gunchleoc** [comment]
No not use vim or any other plain-text editor. Use Poedit or Virtaal, because they come with a translation memory. Poedit also has built-in translation checks.

**Comment by gunchleoc** [comment]
I'll take on this project.

**Comment by eugeneloza** [comment]
Just don't forget that manipulating PO files will destroy a significant portion of previous translations :) I'm almost sure they may be restored semi-automatically, but never studied "how exactly" this should be done.

**Comment by akien-mga** [comment]
It's possible to merge translations from a monolithic PO file into split PO files, I'm doing this for Godot docs translations: https://github.com/godotengine/godot-docs-l10n
(Translations are used by Sphinx to generate the docs as one PO per HTML page, but the translation catalog hosted on Weblate is a megafile with all catalogs collated.)

See https://github.com/godotengine/godot-docs-l10n/blob/master/update.sh for details on how I do it, especially, here is how I merge translations back for the "monolithic" PO file to the per-page small PO files: https://github.com/godotengine/godot-docs-l10n/blob/master/update.sh#L143

**Comment by gunchleoc** [comment]
That's easy enough if we pay attention - just manipulate the Transifex configuration and `tx push` to the new resource. We need to make sure to pull translations before moving stuff - we can also copy everything into the new textdomain before rebuilding the `pot` files.

**Comment by Bertram25** [comment]
@gunchleoc Many thanks for taking care of this. Definitely something that will help me a lot :D 

As for the split, may I suggest this separation?

- [ ] Source code. (src/)
- [ ] Boot sequence (data/boot_menu)
- [ ] Inventory items translations (data/inventory)
- [ ] Entities (characters/enemies) translations (data/entities)
- [ ] Skills (data/skills)
- [ ] Config (data/config)
Story per location:
- [ ] Common parts (data/story/common)
- [ ] Layna Forest (data/story/layna_forest)
... and so on
Would actually be cool to have a system that does a po per data/story sub-folder
- [ ] intro/ending (data/story scripts) they should maybe be moved into a sub-folder.

WDYT?

**Comment by gunchleoc** [comment]
Sounds good. We should think some more about how we want to split the story strings though - for example, the village appears at the beginning and then again later on when the characters return from the forest. For translators, story per chapter would be easier to handle than story per location. Is this feasible from a scripting point of view?

I have fiddled a bit with the CMake code for the string extraction and it is hell to debug, so I'm planning to implement the extraction with Python instead. So, the game plan is:

1. Split the catalogs and translations (`xgettext` calls etc)
2. Modify the engine to handle multiple textdomains
3. `tx pull` the current translations
4. Copy the current translations to all textdomains
5. Create new resources on Transifex and update the Transifex configuration
6. `tx push -s`

**Comment by Bertram25** [comment]
I'm so damn late, but the plan sounds good.

**Comment by gunchleoc** [comment]
Great! It will now probably be some time before I can start working on it, but I'm still interested in taking care of this issue.

**Comment by Bertram25** [comment]
As for the story, I'll move the story into episode sub folders so that it is way easier to have a pot per episode + it will be easier for me to sort my data.

**Comment by Bertram25** [comment]
I'll update the check list in the base description

**Comment by Bertram25** [comment]
Did it. What's left is to update transifex.

**Comment by Bertram25** [comment]
Transifex is now up to date with the new pot files, previous translation injected in them.

**Comment by gunchleoc** [comment]
Thanks! There are still some bugs though

~~~~
[ 88%] Linking CXX executable valyriatear
[ 88%] Built target valyriatear
make[2]: *** No rule to make target 'po/valyriatear.pot', needed by 'data/locale/de/LC_MESSAGES/valyriatear.mo'.  Stop.
CMakeFiles/Makefile2:490: recipe for target 'po/CMakeFiles/translations.dir/all' failed
make[1]: *** [po/CMakeFiles/translations.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2
$ src/valyriatear 
WARNING:src/engine/system.cpp:LoadLanguages:429: 
Couldn't locate gettext .mo file: 'uk_UA/LC_MESSAGES/valyriatear.mo'.
The 'uk_UA' translation will be disabled.
WARNING:src/engine/system.cpp:LoadLanguages:429: 
Couldn't locate gettext .mo file: 'nl_NL/LC_MESSAGES/valyriatear.mo'.
The 'nl_NL' translation will be disabled.
...
~~~~

**Comment by Bertram25** [comment]
@gunchleoc Hmm,
I did a git clean -xdf, reconfigured and recompiled. Everything is fine here:
```
[170/209] Building CXX object src/CMakeFiles/valyriatear.dir/luabind/src/exception_handler.cpp.obj
[171/209] Building CXX object src/CMakeFiles/valyriatear.dir/utils/src/script/script.cpp.obj
[172/209] Generating ../data/locale/fr/LC_MESSAGES
[173/209] Generating ../data/locale/es/LC_MESSAGES
[174/209] Generating ../data/locale/de/LC_MESSAGES
[175/209] Building CXX object src/CMakeFiles/valyriatear.dir/main_options.cpp.obj
[176/209] Building CXX object src/CMakeFiles/valyriatear.dir/modes/pause.cpp.obj
[177/209] Generating ../data/locale/gd/LC_MESSAGES
[178/209] Generating ../data/locale/it/LC_MESSAGES
[179/209] Generating ../data/locale/es/LC_MESSAGES/valyriatear.mo
[180/209] Generating ../data/locale/de/LC_MESSAGES/valyriatear.mo
[181/209] Generating ../data/locale/fr/LC_MESSAGES/valyriatear.mo
[182/209] Generating ../data/locale/nl_NL/LC_MESSAGES
[183/209] Generating ../data/locale/sv/LC_MESSAGES
[184/209] Generating ../data/locale/ru/LC_MESSAGES
[185/209] Generating ../data/locale/gd/LC_MESSAGES/valyriatear.mo
[186/209] Generating ../data/locale/it/LC_MESSAGES/valyriatear.mo
[187/209] Generating ../data/locale/nl_NL/LC_MESSAGES/valyriatear.mo
[188/209] Generating ../data/locale/sv/LC_MESSAGES/valyriatear.mo
[189/209] Generating ../data/locale/ja/LC_MESSAGES
[190/209] Generating ../data/locale/uk_UA/LC_MESSAGES
[191/209] Generating ../data/locale/ru/LC_MESSAGES/valyriatear.mo
[192/209] Generating ../data/locale/pt_PT/LC_MESSAGES
[193/209] Generating ../data/locale/pt_BR/LC_MESSAGES
[194/209] Generating ../data/locale/gl/LC_MESSAGES
[195/209] Building CXX object src/CMakeFiles/valyriatear.dir/main.cpp.obj
[196/209] Generating ../data/locale/pt_PT/LC_MESSAGES/valyriatear.mo
[197/209] Generating ../data/locale/ja/LC_MESSAGES/valyriatear.mo
[198/209] Generating ../data/locale/uk_UA/LC_MESSAGES/valyriatear.mo
[199/209] Generating ../data/locale/pt_BR/LC_MESSAGES/valyriatear.mo
[200/209] Generating ../data/locale/gl/LC_MESSAGES/valyriatear.mo
[201/209] Building CXX object src/CMakeFiles/valyriatear.dir/luabind/src/class_rep.cpp.obj
[202/209] Building CXX object src/CMakeFiles/valyriatear.dir/luabind/src/function.cpp.obj
[203/209] Building CXX object src/CMakeFiles/valyriatear.dir/luabind/src/create_class.cpp.obj
[204/209] Building CXX object src/CMakeFiles/valyriatear.dir/luabind/src/wrapper_base.cpp.obj
[205/209] Building CXX object src/CMakeFiles/valyriatear.dir/luabind/src/class.cpp.obj
[206/209] Building CXX object src/CMakeFiles/valyriatear.dir/luabind/src/class_info.cpp.obj
[207/209] Building CXX object src/CMakeFiles/valyriatear.dir/luabind/src/open.cpp.obj
[208/209] Building CXX object src/CMakeFiles/valyriatear.dir/modes/mode_bindings.cpp.obj
[209/209] Linking CXX executable src\valyriatear.exe
```
Do you, by any chance , have an obsolete CMakeCache.txt file?  (Happens when the macros and other things are updated.)
Can you try from a clean config and tell me?

**Comment by gunchleoc** [comment]
I grabbed a fresh clone and I am still getting the error. Maybe you still have a local file on your computer that needs a git add?

```
[ 86%] Building CXX object src/CMakeFiles/valyriatear.dir/luabind/src/wrapper_base.cpp.o
[ 87%] Building CXX object src/CMakeFiles/valyriatear.dir/luabind/src/open.cpp.o
[ 87%] Building CXX object src/CMakeFiles/valyriatear.dir/luabind/src/lua51compat.cpp.o
[ 88%] Linking CXX executable valyriatear
[ 88%] Built target valyriatear
Scanning dependencies of target translations
[ 89%] Generating ../data/locale/de/LC_MESSAGES
make[2]: *** No rule to make target 'po/valyriatear.pot', needed by 'data/locale/de/LC_MESSAGES/valyriatear.mo'.  Stop.
CMakeFiles/Makefile2:490: recipe for target 'po/CMakeFiles/translations.dir/all' failed
make[1]: *** [po/CMakeFiles/translations.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2


-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- SDL2_INCLUDE_DIR is /usr/include/SDL2
-- SDL2MAIN_LIBRARY is /usr/lib/x86_64-linux-gnu/libSDL2main.a
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Found SDL2_ttf: /usr/lib/x86_64-linux-gnu/libSDL2_ttf.so (found version "2.0.14") 
-- Found SDL2_image: /usr/lib/x86_64-linux-gnu/libSDL2_image.so  
-- Found OpenGL: /usr/lib/x86_64-linux-gnu/libOpenGL.so   
-- Found GLEW: /usr/lib/x86_64-linux-gnu/libGLEW.so  
-- Found OpenAL: /usr/lib/x86_64-linux-gnu/libopenal.so  
-- Found VORBISFILE: optimized;/usr/lib/x86_64-linux-gnu/libvorbisfile.so;debug;/usr/lib/x86_64-linux-gnu/libvorbisfile.so  
-- Found Lua: /usr/lib/x86_64-linux-gnu/liblua5.3.so;/usr/lib/x86_64-linux-gnu/libm.so (found suitable version "5.3.3", minimum required is "5.1") 
-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.11") 
-- Found PNG: /usr/lib/x86_64-linux-gnu/libpng.so (found version "1.6.34") 
-- Found Gettext: /usr/bin/msgmerge (found version "0.19.8.1") 
-- Boost version: 1.65.1
-- Detected Debian System
-- Build type: Release
-- l10n support enabled
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
-- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
-- Looking for gethostbyname
-- Looking for gethostbyname - found
-- Looking for connect
-- Looking for connect - found
-- Looking for remove
-- Looking for remove - found
-- Looking for shmat
-- Looking for shmat - found
-- Looking for IceConnectionNumber in ICE
-- Looking for IceConnectionNumber in ICE - found
-- Found X11: /usr/lib/x86_64-linux-gnu/libX11.so
-- Using included luabind files
-- Using included utils files
-- Configured luabind information file...
-- Configuring done
-- Generating done
-- Build files have been written to: ValyriaTear
Scanning dependencies of target valyriatear
[  1%] Building CXX object src/CMakeFiles/valyriatear.dir/common/global/actors/global_character_handler.cpp.o
[  1%] Building CXX object src/CMakeFiles/valyriatear.dir/common/global/actors/global_actor.cpp.o
...
[ 87%] Building CXX object src/CMakeFiles/valyriatear.dir/luabind/src/lua51compat.cpp.o
[ 88%] Linking CXX executable valyriatear
[ 88%] Built target valyriatear
Scanning dependencies of target translations
[ 89%] Generating ../data/locale/de/LC_MESSAGES
make[2]: *** No rule to make target 'po/valyriatear.pot', needed by 'data/locale/de/LC_MESSAGES/valyriatear.mo'.  Stop.
CMakeFiles/Makefile2:490: recipe for target 'po/CMakeFiles/translations.dir/all' failed
make[1]: *** [po/CMakeFiles/translations.dir/all] Error 2
Makefile:151: recipe for target 'all' failed
make: *** [all] Error 2

```

**Comment by Bertram25** [comment]
@gunchleoc Sorry for the very slow answer.

That's so weird. I did a fresh clone on another machine and compiled and it worked.
It was on Windows 10 with mingw 64. (I'll try again on Linux asap).

Were you on Linux by any chance?

**Comment by gunchleoc** [comment]
Yes, I'm on Linux Mint 19.01

**Comment by Bertram25** [comment]
@gunchleoc I confirm CMake on Linux triggers the bug. I'm confused it din't on Windows. But now I see it, it looks obvious. Sorry for the inconvenience.
I'll have a look.

**Comment by gunchleoc** [comment]
No problem. BTW the bug also shows on the Travis logs:

https://travis-ci.org/ValyriaTear/ValyriaTear/jobs/588232153

**Comment by Bertram25** [comment]
@gunchleoc So, it was already 25 days agom eh. But it should be better now. Can you have a go at testing it again? (I'll quick check on Windows I didn't break anything.)

**Comment by gunchleoc** [comment]
Fix verified. Sorry I didn't get around to testing sooner.
