### ISSUE TITLE
Some torches do not trigger the burning wood sound

### ISSUE THREAD

**Issue by akien-mga** [ValyriaTear/ValyriaTear#364]
I noticed a few torches in the Mt Elbrus Shrine that do not trigger the burning wood sound. At first I thought it was part of a puzzle, but now I think it's just a bug :-p

There me be other affected torches in other places, I just realised it in the shrine (before I'm not sure I had even noticed if torches produced a sound -- though even if I did not "register" it, I'm pretty sure it played a role in making the caves realistic ;).

In each screenshot, the faulty torch is the one next to the player.
![valyriatear-bug-missing-flame-sound png](https://cloud.githubusercontent.com/assets/4701338/3883864/b852c7e8-21a6-11e4-9e5e-7e267fd623c1.jpg)
![valyriatear-bug-missing-flame-sound1 png](https://cloud.githubusercontent.com/assets/4701338/3883865/b998ac26-21a6-11e4-9de5-b20584bb04d6.jpg)
![valyriatear-bug-missing-flame-sound2 png](https://cloud.githubusercontent.com/assets/4701338/3883867/bb0ec3a6-21a6-11e4-91a0-dd82aff3d6c4.jpg)
![valyriatear-bug-missing-flame-sound3 png](https://cloud.githubusercontent.com/assets/4701338/3883869/bc4d8bc6-21a6-11e4-8b9f-5923bdded050.jpg)

If it's something that can be fixed in the lua scripts, I'll gladly have a look and propose a pull request to fix this, just to start digging into the code :-)

**Comment by Bertram25** [comment]
Done! Phew ... :)

**Comment by Bertram25** [comment]
Will close when merging the start of new game balancing

**Comment by akien-mga** [comment]
He's aliiiiiiiive o_O
