### ISSUE TITLE
Add status effects and other hints within the game

### ISSUE THREAD

**Issue by Bertram25** [ValyriaTear/ValyriaTear#387]
Tips to add throughout the game:
- [x] Running
- [x] Equipping
- [x] Improve skills
- [x] Stamina handling
- [x] You can use 'Escape Smoke' to flee regular battles.
- [x] Encounters (ambushes and first strikes)
- [x] Characters stats & status effects.
- [x] Moon juice potion restores skill points, useful for skills and magic.

**Comment by Suitecake** [comment]
Definitions of various negative statuses would be really helpful (IE, exactly how Sleep works)

**Comment by Bertram25** [comment]
Hints about what spell is good against what kind of opponent, too, I'd say. :)
Easy enough, even if I'd like it to be read from a lua config file so we can expand it at will.

**Comment by Bertram25** [comment]
Something must be found in a better way than the game over screen. Yet, VT has got no loading screen at all yet. Probably a battle tutorial will have to be added within the story to help with status effect. I'll add a way to get some hint about this.

**Comment by Bertram25** [comment]
I'll add several hint stones throughout the game, about:
- stamina handling (and running)
- characters stats & status effects.
- encounters (ambushes and first strikes)

**Comment by Bertram25** [comment]
Hints will have to be placed during the beginning of the game (Why not through Kalya.)
