### ISSUE TITLE
Fix character-based sentences when the leading character is telling them

### ISSUE THREAD

**Issue by Bertram25** [ValyriaTear/ValyriaTear#415]
This is useful to be able to Ukrainian/Russian translations.

At minimum: contextual translation must be used for each genders in such cases.

**Comment by Bertram25** [comment]
Note to self: Search for sentence told by the hero sprite directly and watch for "personal" or self-told sentences.

**Comment by gunchleoc** [comment]
I recommend using `pgettext` for the disambiguation. This will also allow us to have the same string duplicated for the 2 genders when necessary. We will need to ship our own `gettext.h` file with some additional macros for that. There's an improved version for that on Widelands - please feel free to grab: https://bazaar.launchpad.net/~widelands-dev/widelands/trunk/view/head:/src/third_party/gettext/gettext.h

**Comment by Bertram25** [comment]
Thanks for the link.
Just to point out, as it may be slightly different, the true issue is to make possible to have translation based on the lead characters, and not forcefully the gender, which is somehow a trick to make it work.
So I may adapt the engine to do so, instead. As later, I hope you will have more than 2 fully playable characters.

**Comment by Bertram25** [comment]
Note to self: search for '(text, hero' for instances of the issue.

**Comment by Bertram25** [comment]
After searching a bit, as dialogues are loaded once at the same time than the script and because the "hero" sprite is reloaded to be the party leader afterward, I'd need to be able to tell the dialogue manager the dialogue is to be reloaded depending on the sprite name. And this becomes nasty.
Instead, I'll do what I have naturally done with other scene, I'll make both character appear, and the actual sprite speak to fix the dialogue gender issues.
