### ISSUE TITLE
High-bouncing numbers on fighting skeletons

### ISSUE THREAD

**Issue by suitecake** [ValyriaTear/ValyriaTear#445]
I left the game running over night (paused IIRC) and when I came back in the morning and fought some skeletons in the shrine, the damage numbers (both on my characters and on the skeletons) bounced VERY high (spawning just below off-screen and arching high off-screen). Turning the game off and starting it back up produced normal arching numbers.

**Comment by Suitecake** [comment]
I'm running windowed, in 1680 x 1050 (on a 1920 x 1200 monitor)

**Comment by Bertram25** [comment]
Lol, I see what happened.
The frame time diff wasn't reset after unpausing the game, making this funny behaviour happen.

I'll fix this asap. Thanks for the report.

**Comment by Bertram25** [comment]
I'm reopening this as the performance settings is triggering the bug.
Also, the battle intro effect is broken wit performance.
