### ISSUE TITLE
Temporary images are mishandled, making certain menu backgrounds disappear when changing the resolution and other similar bugs.

### ISSUE THREAD

**Issue by Bertram25** [ValyriaTear/ValyriaTear#455]
The temp images are created in a false "img/temp" folder, as seen here:
https://github.com/Bertram25/ValyriaTear/blob/master/src/engine/video/texture_controller.cpp#L324
```c++
bool TextureController::_DeleteTempTextures()
{
    return vt_utils::CleanDirectory("img/temp");
}
```

This should be changed so that the temp folder is created specificly for the game as a per platform fashion. (The folder name can be determined at app start, just like other system folders.)

There are other "img/temp/" reference in the code, so one will have to care of those as well.

**Comment by authenticate** [comment]
I was trying to fix a resolution bug in map mode.  If you change the resolution of the game in map mode, the map tiles will not properly scale with the new resolution.

Are these issues related?  I was not able to diagnose what exactly was causing the map resolution bug.

**Comment by Bertram25** [comment]
@authenticate 
Hi :)

Are these issues related? 

I do think they aren't. The current bug is about the snapshot taken just before opening a menu mode or the pause mode, as used as a background for those modes. If you change the resolution, then the snapshot is lost and the background becomes black.

Here, I think we have a different and new bug. In your case, I don't know whether the tiles need rescaling or whether the rescaling is wrong. Let's talk about this in a new issue?

**Comment by authenticate** [comment]
Thanks for the update.  I pushed up a pull request to address the resolution bug in map mode (For future reference, not the problem described in this issue.).  I think it's in good shape. :)

**Comment by Bertram25** [comment]
Yes, it is, I just merged. Thanks a lot for the help. :)

**Comment by authenticate** [comment]
I copied some of my comments from a pull request and placed them below for reference and discussion.

>I think we need to redraw each game state in the game state stack and capture new background images on a resolution change.
>
>For example, if we have the following game state stack
>
>C
>B
>A
>
>where game state 'C' is the current game state and it depends on background images from game states 'B' and 'A'.  I think we need to pop the entire stack and start with 'A'.  Redraw 'A'.  Put 'A' back on the stack.  Then, have game state 'B' capture a new image of 'A'.  Redraw 'B'.  Put 'B' back on the stack.  Have game state 'C' capture a new image of 'B'.  Redraw 'C'.  Put 'C' back on the stack.

**Comment by Bertram25** [comment]
> I think we need to redraw each game state in the game state stack and capture new background images on a resolution change.

Here I wonder: Isn't it possible to simply keep the texture in memory and redraw it afterward?
AFAIK, we always keep a viewport of 1024x768 whatever the resolution used so the image quality shoudn't matter.
Also, with SDL2, AFAIK, the GL context isn't lost when resizing so I wonder whether the corresponding texture is still in memory.
And if not, maybe we can keep the ImageMemory class buffer and reupload the texture after resolution change?

Could you tell me a bit more about what's behind your mind?
(I know your comment is everything but innocent ;])

**Comment by authenticate** [comment]
>AFAIK, we always keep a viewport of 1024x768 whatever the resolution used so the image quality shoudn't matter.

That's a good point.  I forgot about that.

I think the game uses the resolution of the game itself for the final texture resolution on disk for temporary textures.  However, if they are stored internally at 1024x768, that would make things much easier.  We also might be able to stop storing them to disk and reloading them all together.

I was afraid, in order to generate the correct resolution texture, we would need to go to each game state in the game state stack and re-generate the textures manually.  Hopefully, the solution is easier and less involved than this. :)

**Comment by authenticate** [comment]
I think it might be more complicated.

I think MapMode renders the map itself at 1024x768.  Then, MapMode scales map scales appropriately to resolution of the game.

However, in general, the viewport will match the resolution of the game (except for things like the minimap).

The following function creates the temporary textures.

```
StillImage VideoEngine::CaptureScreen() throw(Exception)
```

```
// Retrieve width/height of the viewport. viewport_dimensions[2] is the width, [3] is the height
GLint viewport_dimensions[4] = { 0, 0, 0, 0 };
glGetIntegerv(GL_VIEWPORT, viewport_dimensions);
```

This viewport was equal to the game's resolution in the test cases I was running. :(

I think you are correct in keeping the texture in memory and not having to store them on disk.  However, I think we will need to provide a mechanism for the game to regenerate these textures on resolution change.

**Comment by Bertram25** [comment]
Thanks for analysis @authenticate and sorry again for the slow answer.

> This viewport was equal to the game's resolution in the test cases I was running. :(

I think you're right: As seen in the _UpdateViewportMetrics() function:
https://github.com/Bertram25/ValyriaTear/blob/master/src/engine/video/video.cpp#L564

The viewport will indeed update itself to match a 4:3 resolution within the available screen width/height.
And in case like 800x600, 1024x780, ... it will match 1:1 the game screen resolution.

Now for our problem, is the screenshot taking the offsets in account for instance? Because I didn't see any hints that it does in CaptureScreen().

Regards,

**Comment by Bertram25** [comment]
Fixed by @authenticate in https://github.com/ValyriaTear/ValyriaTear/commit/35c0e68dc2ebfe05680a4e2b6278fbbd8ce15b1f

thanks a lot!!
