### ISSUE TITLE
probable small performance and maintenance improvements in ustring

### ISSUE THREAD

**Issue by bmorel** [ValyriaTear/ValyriaTear#462]
Hi. A new issue, not related to any bug.

When I played with the source code this week end, with the very old computer I use when I am not at home, I noticed a class named ustring. I have, only for pure fun, reimplemented lot of it's methods, using more stuff from the STL (reserving memory before push_backs, or using std::vector::insert when possible).

I won't just post those rewrites, because I would like to know what are the issues with the std::wstring class before. Otherwise, it would be stupid to submit possible regressions :)

Also, considering the difference between binaries when compiling in debug mode, my optimizations made the (debug) binary bigger. Less lines of code (LoC reduced by 25% for the file ustring.cpp, more or less), but bigger binary (so, potentially slower code!). If ustring is used in lot of places and with a lot of strings, there *could* be a small improvement if it was replaced, either by a  better implementation of several methods or by using more of the standard functions. It would also be easier to maintain code if there could be more explicit hints about why not use std::wstring.

I will compile VT on a my desktop computer tomorrow. I should even be able to play, on this one hehe!

**Comment by Bertram25** [comment]
Hey @bmorel  :)

> When I played with the source code this week end, with the very old computer I use when I am not at home, I noticed a class named ustring. I have, only for pure fun, reimplemented lot of it's methods, using more stuff from the STL (reserving memory before push_backs, or using std::vector::insert when possible).

> Also, considering the difference between binaries when compiling in debug mode, my optimizations made the (debug) binary bigger. Less lines of code (LoC reduced by 25% for the file ustring.cpp, more or less), but bigger binary (so, potentially slower code!). If ustring is used in lot of places and with a lot of strings, there could be a small improvement if it was replaced, either by a better implementation of several methods or by using more of the standard functions. It would also be easier to maintain code if there could be more explicit hints about why not use std::wstring.

Well, I must say without seeing the aforementionned changes, I can't tell much. But binaries not stripped and not optimized for size tend to grow easily.

> I won't just post those rewrites, because I would like to know what are the issues with the std::wstring class before. Otherwise, it would be stupid to submit possible regressions :)

I'll be honest. The ustring class is from HoA so maybe @rootslinux will know more. From what I can tell, the author wanted to have something custom made to tailor it to his exact needs.
I wonder whether we could simply use a well-used and standard objects such as a wstring in that case. Could be worth the try and more convenient for people playing with the code like us. ;)

> I will compile VT on a my desktop computer tomorrow. I should even be able to play, on this one hehe!

Good :) I hope you'll enjoy the ride.

**Comment by bmorel** [comment]
> Well, I must say that without seeing the aforementioned changes, I can't tell much. But binaries not stripped and not optimized for size tend to grow easily.

Oh, the changes are pretty trivial. Take a look at the file, and thinks that I was able to quickly replace all push_backs by methods more efficient of the STL. For example, instead of a for loop which only does a push at each iteration, using insert. Sometimes splitting the loop to know in advance how many things to insert.
This would avoid tons of reallocations, in theory. Depending on the size of the vectors and on the implementations of std::vector (which does not allocate precisely what it needs when it needs to reallocate because of a push_back, but reserves a little more, just in case. So, people should use std::vector::reserve before doing several push_backs, when it's possible. And it often is.).

> But binaries not stripped and not optimized for size tend to grow easily.

Indeed. But I prefer to say things directly. I have no actual proof that there would be a real improvement.

> The ustring class is from HoA so maybe @rootslinux will know more. From what I can tell, the author wanted to have something custom made to tailor it to his exact needs.
 I wonder whether we could simply use a well-used and standard object such as a wstring in that case. Could be worth the try and more convenient for people playing with the code like us. ;)

We probably could get some ease, but, on the other hand, maybe he did that for an actual good reason. So, the easier would be to ask him, if you can. Otherwise, a simple refactor like what I did would be better: the same features, the same bugs, but using more standard functions instead of reimplementing those. I like reinventing the wheel, but I try to avoid it on big projects :)
Reproducing bugs is important when refactoring, because sometimes, features depends on bugs. So, the first step is to refactor but keeping bugs, just in case. Usually it makes bugs more obvious, and then you can try to kill them.

> Good :) I hope you'll enjoy the ride.

I do. As I said 2 years ago, I like riding with small codebases that I can try to improve. And I like playing games, too.
Well, I'm stuck in a place you added after Harlequin (ok, I have finally noticed that some reductions in walls are corridors, so I may advance anew, but memleak killed me again), I have noticed a very huge memory leek (memory consumption after a little more than 2 hours of game: 4Gb. I had to restart the game from scratch, lost my 1-2 year old saves :) ). I thing those issues are more critical than hypothetical or minor perf improvements, so I'm playing with what I think is the cause. More info in another issue ;)

I also have noticed code which was probably migrated from C code to C++, and am fixing that. Which could be a source of memleaks. I'll post the changes I would suggest to ustring tomorrow. Hum. In few hours, actually hehe.

PS: I like the skins of skeletons.

**Comment by bmorel** [comment]
I just pushed it on my version of the repo, in branch refactoring. I do not make a push request with it because I also did some changes in ImageMemory, which seems to be ok (I have not noticed regressions) but I think it's possible to improve things more.

**Comment by Bertram25** [comment]
For reference: https://github.com/bmorel/ValyriaTear/commit/a1e27dfc857a91f93988faabd771283570696f7c

**Comment by Bertram25** [comment]
Considered done with: https://github.com/ValyriaTear/ValyriaTear/commit/76817d0c84140d73f80c2e83cd49a65a71baaeea

A nice improvement could be to see whether we can use wstring as a standard replacer.
