### ISSUE TITLE
``git submodule update --init --remote`` fails

### ISSUE THREAD

**Issue by kozross** [ValyriaTear/ValyriaTear#486]
Exact error message reproduced below:

     Cloning into 'src/luabind'...
     fatal: remote error: 
       ValyriaTear/luabind.git master is not a valid repository name
       Email support@github.com for help
    Clone of 'git://github.com/ValyriaTear/luabind.git master' into submodule path 'src/luabind' failed

**Comment by shirishag75** [comment]
+1 here.

**Comment by Bertram25** [comment]
Hi @kozross @shirishag75 :)

Could you try replacing the url part with:
`https://github.com/ValyriaTear/luabind.git`
in the `.gitmodules` file and tell whether it is working?
The complete line would be:
` url = https://github.com/ValyriaTear/luabind.git master`

**Comment by kozross** [comment]
Same issue. For some reason, the last line also doesn't change (the url starts with ``git`` rather than ``https`` despite me making the change you asked for).

**Comment by Bertram25** [comment]
@kozross Hi again, Sorry for the slow answer, but my spare-time is scarce those days. ;)

I just fixed the submodule url in this commit:
c537f324575df8d21c08eec5ad82b4b887234c5a

Could you pull the latest changes and then do:
```
git submodule sync
git submodule update --init --remote
```
Thanks!

**Comment by kozross** [comment]
@Bertram25 OK, that fixed that issue. Thanks!
