### ISSUE TITLE
No 'uninstall' target

### ISSUE THREAD

**Issue by kozross** [ValyriaTear/ValyriaTear#490]
This is a little mean - it makes it difficult to uninstall this after you use 'sudo make install'.

**Comment by Bertram25** [comment]
Indeed. Yet, keep in mind that this will uninstall where the latest prefix was set. But otherwise, I'm fine adding it. :)

**Comment by kozross** [comment]
That's fine - this is the default behaviour of most projects anyway.

**Comment by Bertram25** [comment]
@kozross Have fun!
