### ISSUE TITLE
Saving PNG image bug.

### ISSUE THREAD

**Issue by authenticate** [ValyriaTear/ValyriaTear#497]
Hi,

When swapping between certain resolutions in map mode through the pause menu, the background screen captured image has what appears to be a stride problem.

Consider the following images

![image_one](https://cloud.githubusercontent.com/assets/4543259/11018301/b0201efe-8591-11e5-8dc2-9cf453327340.png)

![image_two](https://cloud.githubusercontent.com/assets/4543259/11018304/bd1f5cf0-8591-11e5-89af-d755783c6f25.png)

Note: This final image is the temporary image from the hard drive.

![capture_screen14](https://cloud.githubusercontent.com/assets/4543259/11018305/c2f400ea-8591-11e5-8348-b56580993d3c.png)

I did some limited investigation.  I originally felt that the issue was in the following function

```c++
void ImageMemory::CopyFromImage(BaseTexture *img)
```

However, I am not entirely sure.  The code in this function does appear correct to me.  Maybe I missed something?

**Comment by authenticate** [comment]
Note: Accepting #498 will require this issue to be reproduced another way.

**Comment by Bertram25** [comment]
I could reproduce this issue once, but no more afterward. Does this still happen before #494 #495 ?

**Comment by Bertram25** [comment]
N.B.: #498 may have hidden/fixed this bug.

**Comment by authenticate** [comment]
I believe the bug happens starting at 671454164e6c5d5b74dd7794a6ee3b387a038f7f.

In addition, #498 hides the bug since we no longer save background images to disk.  They are kept in memory.  However, I am pretty confident the issue is still present somewhere.

**Comment by Bertram25** [comment]
Arg, seems I caused a regression... Do you want me to create a branch where removal of the save to disk feature is reverted?

**Comment by authenticate** [comment]
I wouldn't worry about making a branch or anything.  It shouldn't be too difficult to go back to the old commit and debug.

Screen shots appear to work correctly.  The capture screen shot functionality does not seem to execute the code with the bug in it.  Hopefully that will help in tracking down the issue.
