### ISSUE TITLE
Fix Build and/or Travis CI

### ISSUE THREAD

**Issue by Bertram25** [ValyriaTear/ValyriaTear#504]
As seen in recent builds, but also there:
http://forum.freegamedev.net/viewtopic.php?f=76&t=6636

**Comment by akien-mga** [comment]
It should likely be fixed here: https://github.com/ValyriaTear/ValyriaTear/blob/master/.travis.yml#L5-L6

**Comment by Bertram25** [comment]
Thanks. But I think not only. Certain targets have changed and equivalent travis.yml should be added to the two other projects.

**Comment by Bertram25** [comment]
This is done with:
https://github.com/ValyriaTear/ValyriaTear/commit/9fe36fa434d1ec213e438175c4a8f48c74394c6e

Actually, @akien-mga did the job. ;)
