### ISSUE TITLE
Specify path to lookup installed data files

### ISSUE THREAD

**Issue by hagabaka** [ValyriaTear/ValyriaTear#505]
On Linux, the installed game executable seems to look for data files directly in the current directory, but they are actually installed to `PREFIX/share/valyriatear`. Is there a way to specify the location where the game looks for data?

**Comment by akien-mga** [comment]
Hm, if I remember correctly it it's working out of the box; if you do have data files in the current directory though, they will be used in priority over the system installed ones.

**Comment by hagabaka** [comment]
If I run the installed `valyriatear` from an arbitrary directory, it quits with
```
ERROR:/home/hagabaka/Projects/PKGBUILDs/valyria-tear-git/src/ValyriaTear/src/modes/map/map_minimap.cpp:SDLSurfaceController:56: 
Couldn't create the white noise image for the collision map: Couldn't open data/gui/map/minimap_collision.png
connect(2) call to /dev/shm/jack-1000/default/jack_0 failed (err=No such file or directory)
attempt to connect to server failed
ERROR:/home/hagabaka/Projects/PKGBUILDs/valyria-tear-git/src/ValyriaTear/src/engine/script/script_read.cpp:OpenFile:48: 
Attempted to open unavailable file: data/config/themes.lua
ERROR:/home/hagabaka/Projects/PKGBUILDs/valyria-tear-git/src/ValyriaTear/src/main.cpp:LoadGUIThemes:272: 
Couldn't open theme file: data/config/themes.lua
```
If I run it from `/usr/share/valyriatear`, it works (the error about jack is still there but is harmless).

**Comment by Bertram25** [comment]
Hi @hagabaka and sorry for the slow answer.

Some time has passed since it looked a that part correctly, but you should be able to specify the data install prefix when invoking CMake, e.g.:
```cmake -DCMAKE_INSTALL_PREFIX="/path/to/prefix/folder" .```

valyriatear should then look for it after checking for local data path.

Is it helping you?

**Comment by hagabaka** [comment]
I'm already using `cmake -DCMAKE_INSTALL_PREFIX=/usr`.

Actually the problem is in  [line 518 of main.cpp](https://github.com/ValyriaTear/ValyriaTear/blob/master/src/main.cpp#L518):
```c++
        // Look for data files in DATADIR only if they are not available in the current directory.
        if(std::ifstream("data/config/settings.lua").bad()) {
            if(chdir(PKG_DATADIR) != 0) {
                throw Exception("ERROR: failed to change directory to data location", __FILE__, __LINE__, __FUNCTION__);
            }
        }
```
If I change the file check to `!std::ifstream("data/config/settings.lua").good()`, the problem is fixed. According to [cppreference](http://en.cppreference.com/w/cpp/io/ios_base/iostate), the "failbit", not the "badbit" is set when a file cannot be opened. `good()` checks that none of failbit, badbit, and eofbit is set, while`bad()` just checks the badbit.

Another problem is that the minimap collision code is run before this `chdir`, so I still get the error
```
Couldn't create the white noise image for the collision map: Couldn't open data/gui/map/minimap_collision.png
```
But the game still starts. I can try to fix this and create a pull request in the next few days.

**Comment by hagabaka** [comment]
I created the pull request #507 to fix the crash.

About the error on "white noise image for the collision map", the code triggering this is in [line 83 of src/modes/map/map_minimap.cpp](https://github.com/ValyriaTear/ValyriaTear/blob/master/src/modes/map/map_minimap.cpp#L83)
```
//! \brief A white noise texture.
const SDLSurfaceController WHITE_NOISE("data/gui/map/minimap_collision.png");

//! \brief A helper function to prepare a SDL_Surface.
static bool _PrepareSurface(SDL_Surface* temp_surface)
{
    SDL_Rect r = { 0, 0, 0, 0 };

    // Prepare the surface with the image.  Tile the white noise image onto the surface with full alpha.
    for(int x = 0; x < temp_surface->w; x += WHITE_NOISE._surface->w) {
        r.x = x;
        for(int y = 0; y < temp_surface->h; y += WHITE_NOISE._surface->h) {
            r.y = y;
            if(SDL_BlitSurface(WHITE_NOISE._surface, nullptr, temp_surface, &r)) {
```
It attempts to initialize a global constant with the content of file "data/gui/map/minimap_collision.png", but since it's in the global scope, this happens before the `chdir` call in main(). The constant `WHITE_NOISE` is not used anywhere else, so the initialization could be just moved into `_PrepareSurface` to fix this. But `_PrepareSurface` itself isn't called anywhere, so maybe this is old code that could be removed?

**Comment by Bertram25** [comment]
> It attempts to initialize a global constant with the content of file "data/gui/map/minimap_collision.png", but since it's in the global scope, this happens before the chdir call in main(). The constant WHITE_NOISE is not used anywhere else, so the initialization could be just moved into _PrepareSurface to fix this. But _PrepareSurface itself isn't called anywhere, so maybe this is old code that could be removed?

I'll check this asap. Thanks for fixing the rest, though. :)

**Comment by Bertram25** [comment]
Hey, 

> But _PrepareSurface itself isn't called anywhere, so maybe this is old code that could be removed?

I just checked and _PrepareSurface() is called by _CreateProcedurally(), which is what happens when the minimap is created from the map data instead of from a given prepared file. So it is used in the end. I'll have a go at fixing this.
