### ISSUE TITLE
First Layna Forest Cave background isn't shown anymore

### ISSUE THREAD

**Issue by Bertram25** [ValyriaTear/ValyriaTear#514]
The cave map script is in : data/story/layna_forest/lana_forest_cave1_1* files.

This map script is loading the following script:
layna_forest_caves_background_anim.lua
And the background function there is called (I tested) but the still image is not drawn.

**Comment by Bertram25** [comment]
@authenticate For information. This might be linked to the graphic pipeline, or not.

**Comment by authenticate** [comment]
I think pull request #518 should address this issue.

**Comment by Bertram25** [comment]
Fixed with #518 . Thanks a lot @authenticate
