### ISSUE TITLE
Binary Releases for Windows and OS X

### ISSUE THREAD

**Issue by authenticate** [ValyriaTear/ValyriaTear#527]
Hi,

I noticed there are some releases in the "Releases" tab on Github.  However, the download links only contain source.

For Windows and OS X, I think it would be beneficial to also have binary downloads.

This is not a super critical feature or request.  I just thought it would be nice to also have binary download options right from Github for the project.

Thanks.

**Comment by Bertram25** [comment]
Hi @authenticate !
True. I guess I never did it because source forge already provided support for it, but yes, I'll upload those ones as true release once I've got a better bandwidth. (Next week hopefully)

**Comment by Bertram25** [comment]
Also, once your latest PR is in (with some fixes to the particle effects), I think I'll release a developer builds to show off progresses made so far. (Even if no story has been added yet.)

**Comment by gunchleoc** [comment]
How about using [AppVeyor](https://www.appveyor.com/) for Windows builds? Windows builds with MSys2 will be fixed with https://github.com/ValyriaTear/ValyriaTear/pull/621, so all we'll need to do is to add an `appveyor-ci.yml` and call NSIS from the command line. I have a file that I could adapt if you guys will create an AppVeyor account.

**Comment by Bertram25** [comment]
+1 for the appveyor windows build :D

**Comment by gunchleoc** [comment]
How do we want to organize this? After the Windows branch has been merged, we could do it like this:

1. I'll provide a first draft of the `appveyor-ci.yml` and create PR for testing, not to be merged yet
2. You'll set up an AppVeyor account and link it to GitHub to see if it gets triggered properly
3. I'll fix any remaining issues with the `appveyor-ci.yml`
4. I'll document how to use the Appveyor builds
5. PR gets merged after code review

**Comment by Bertram25** [comment]
Feel free to ahead. :)
I'll create the appveyor account whenever possible.

**Comment by Bertram25** [comment]
Worked for the main releases. I'm closing the issue. Many thanks!

**Comment by gunchleoc** [comment]
AppVeyor does the job for Windows, but not for Mac. Do we want to open a separate issue for Mac?

**Comment by Bertram25** [comment]
@gunchleoc  I guess we do, I don't own a Mac and I would need to borrow one + fiddle with XCode. So I wouldn't make this a high priority issue unless a Mac fellow shows up.
