### ISSUE TITLE
Text scissoring bug dependent on resolution

### ISSUE THREAD

**Issue by Bertram25** [ValyriaTear/ValyriaTear#528]
Depending on the resolution used, some texts may be badly scissored.

This can be rather easily worked around, but a better thing would be to fix it while one can reproduce it easily.
Notice the "Bare-Hand' text in the command menu:
Using 768x576:
![screenshot_12](https://cloud.githubusercontent.com/assets/765917/13410807/006e622e-df3a-11e5-8928-859c503358fd.png)
Using 800x600:
![screenshot_13](https://cloud.githubusercontent.com/assets/765917/13410839/2cd4a1ca-df3a-11e5-89d7-e267ee6efdfe.png)

**Comment by Bertram25** [comment]
@authenticate For you to know. May be linked to scissoring improvements. Cheers!

**Comment by authenticate** [comment]
I am pretty sure you are right.  I will take a look at it.

**Comment by authenticate** [comment]
Pull request #534 should clean this up.

**Comment by Bertram25** [comment]
Indeed fixed with #534
