### ISSUE TITLE
luabind file missing error

### ISSUE THREAD

**Issue by chlin501** [ValyriaTear/ValyriaTear#536]
When executing cmake . (or mkdir build && cd build && cmake ..), it throws following error message: 

``CMake Error: File /path/to/ValyriaTear/src/luabind/build_information.hpp.cmake_in does not exist.
CMake Error at src/CMakeLists.txt:126 (CONFIGURE_FILE):
  configure_file Problem configuring file``

After installing luabind-dev package the error still exists. 
Environment: debian stretch/sid, cmake version 3.4.1.

**Comment by Bertram25** [comment]
Hi @chlin501 

As stated in the README file:

> If you have checked it out from the Git repository, run this first to get the latest luabind code: `git submodule update --init --remote --force`

Cheers,
