### ISSUE TITLE
FTBFS for 1.0.0 with GCC 5

### ISSUE THREAD

**Issue by akien-mga** [ValyriaTear/ValyriaTear#541]
Hi @Bertram25,

I just noticed that my valyriatear package has been failing autobuilds in Mageia since Aug 2015, which appears to be when we introduced GCC 5.3.1 instead of 4.9.2: http://pkgsubmit.mageia.org/autobuild/history.php?package=valyriatear

The issue seems to be related to luabind:
```
In file included from /home/pterjan/rpmbuild/BUILD/ValyriaTear-1.0.0/src/luabind/luabind/detail/call_member.hpp:34:0,
                 from /home/pterjan/rpmbuild/BUILD/ValyriaTear-1.0.0/src/luabind/luabind/wrapper_base.hpp:31,
                 from /home/pterjan/rpmbuild/BUILD/ValyriaTear-1.0.0/src/luabind/luabind/back_reference.hpp:27,
                 from /home/pterjan/rpmbuild/BUILD/ValyriaTear-1.0.0/src/luabind/luabind/class.hpp:93,
                 from /home/pterjan/rpmbuild/BUILD/ValyriaTear-1.0.0/src/luabind/luabind/luabind.hpp:28,
                 from /home/pterjan/rpmbuild/BUILD/ValyriaTear-1.0.0/src/utils/utils_pch.h:137:
/home/pterjan/rpmbuild/BUILD/ValyriaTear-1.0.0/src/luabind/luabind/object.hpp: In function 'bool luabind::detail::operator==(const luabind::detail::basic_iterator<luabind::detail::basic_access>&, const luabind::detail::basic_iterator<luabind::detail::basic_access>&)':
/home/pterjan/rpmbuild/BUILD/ValyriaTear-1.0.0/src/luabind/luabind/object.hpp:556:37: error: no matching function for call to 'operator==(const luabind::detail::basic_iterator<luabind::detail::basic_access>&, const luabind::detail::basic_iterator<luabind::detail::basic_access>&)'
       return boost::operator op(x, y); \
                                     ^
```

See full build log: http://pkgsubmit.mageia.org/autobuild/cauldron/x86_64/core/2016-03-20/valyriatear-1.0.0-3.mga6.src.rpm/build.0.20160320140810.log

I haven't tried building HEAD recently but I'd expect it to behave better with the forked luabind. Any idea about the best way to solve it in my case? Should I package a git snapshot as a pre-release of 1.1, or try to patch luabind to have 1.0.0 build?

**Comment by Bertram25** [comment]
@akien-mga Hmm, I'll need some more time to have a look carefully. I'll do that at the same time than reviewing @authenticate 's code. :)

**Comment by akien-mga** [comment]
I'm now trying to build HEAD to see if it works better (I suppose it will). If it works fine, do you think I can use your luabind submodule as a drop-in replacement for the embedded version in 1.0.0?

**Comment by akien-mga** [comment]
I managed to build 1.0.0 against GCC 5.3 by replacing the bundled version with the new submodule and using this patch to adapt the buildsystem: http://svnweb.mageia.org/packages/cauldron/valyriatear/current/SOURCES/valyriatear-1.0.0-mga-cmake-luabind.patch?view=markup

I then had one issue when building with `CMAKE_BUILD_TYPE=RelWithDebInfo` on i586:
- First with PCH compilation enabled:
```
cd /home/iurt/rpmbuild/BUILD/ValyriaTear-1.0.0/build/src && /usr/bin/c++ -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fomit-frame-pointer -march=i586 -mtune=generic -fasynchronous-unwind-tables -Wall -Wextra -g -pg -DPACKAGE_VERSION=\"0.1.0\" -DPKG_DATADIR=\"/usr/share/games/valyriatear/\" -DLOCALEDIR=\"/usr/share/locale/\" -DPKG_NAME=\"valyriatear/\" -DDEBUG -DUSE_X11 -c /home/iurt/rpmbuild/BUILD/ValyriaTear-1.0.0/src/utils/utils_pch.h -o /home/iurt/rpmbuild/BUILD/ValyriaTear-1.0.0/src/utils/utils_pch.h.gch -I /usr/include -I /home/iurt/rpmbuild/BUILD/ValyriaTear-1.0.0/src -I /usr/include/SDL -I /usr/include/SDL -I /usr/include/SDL -I /usr/include -I /usr/include/AL -I /usr/include -I /usr/include -I /usr/include -I /usr/include -I /usr/include -I /home/iurt/rpmbuild/BUILD/ValyriaTear-1.0.0/src/luabind
c++: error: -pg and -fomit-frame-pointer are incompatible
src/CMakeFiles/valyriatear.dir/build.make:64: recipe for target '../src/utils/utils_pch.h.gch' failed
```
Full build log: http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20160413170740.akien.duvel.38582/log/valyriatear-1.0.0-4.mga6/build.0.20160413170804.log
- And then with PCH compilation disabled:
```
[ 15%] Building CXX object src/CMakeFiles/valyriatear.dir/common/global/global.cpp.o
cd /home/iurt/rpmbuild/BUILD/ValyriaTear-1.0.0/build/src && /usr/bin/c++    -I/home/iurt/rpmbuild/BUILD/ValyriaTear-1.0.0/src -I/usr/include/SDL -I/usr/include/AL -I/home/iurt/rpmbuild/BUILD/ValyriaTear-1.0.0/src/luabind  -O2 -g -pipe -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fstack-protector --param=ssp-buffer-size=4 -fomit-frame-pointer -march=i586 -mtune=generic -fasynchronous-unwind-tables  -Wall -Wextra -g -pg -DNDEBUG   -DPACKAGE_VERSION=\"0.1.0\" -DPKG_DATADIR=\"/usr/share/games/valyriatear/\" -DLOCALEDIR=\"/usr/share/locale/\" -DPKG_NAME=\"valyriatear/\" -DDEBUG -DUSE_X11 -o CMakeFiles/valyriatear.dir/common/global/global.cpp.o -c /home/iurt/rpmbuild/BUILD/ValyriaTear-1.0.0/src/common/global/global.cpp
c++: error: -pg and -fomit-frame-pointer are incompatible
src/CMakeFiles/valyriatear.dir/build.make:65: recipe for target 'src/CMakeFiles/valyriatear.dir/common/global/global.cpp.o' failed
```
Full build log: http://pkgsubmit.mageia.org/uploads/failure/cauldron/core/release/20160413171153.akien.duvel.10016/log/valyriatear-1.0.0-4.mga6/build.0.20160413171205.log

So it looks like you're defining two conflicting build flags on i586. The offending definition is there: https://github.com/ValyriaTear/ValyriaTear/blob/master/src/CMakeLists.txt#L70-L81
Two things:
- I'm not sure defining `-DDEBUG` on RelWithDebInfo builds is a good idea, this build type is not debug mode, but is supposed to have enhanced debug infos in the binary to e.g. debug with gdb.
- The conflicting flags thing needs to be sorted out (it's still the same flags in master).

**Comment by Bertram25** [comment]
@akien-mga Thanks for the job done on this one. I'll try to sort this out now. Could you review me once this is done? (I'll be on OD stuff afterwards)

**Comment by Bertram25** [comment]
> I'm not sure defining -DDEBUG on RelWithDebInfo builds is a good idea, this build type is not debug mode, but is supposed to have enhanced debug infos in the binary to e.g. debug with gdb.

This is true, I'll remove the type `RelWithDebInfo` from the `-DDEBUG` thing.

Would this work for you?
```diff
diff --git a/src/CMakeLists.txt b/src/CMakeLists.txt
index ba9ef4f..2435580 100644
--- a/src/CMakeLists.txt
+++ b/src/CMakeLists.txt
@@ -69,14 +69,18 @@ ENDIF()
 
 IF (CMAKE_BUILD_TYPE)
     STRING(TOLOWER ${CMAKE_BUILD_TYPE} CMAKE_BUILD_TYPE_TOLOWER)
-    IF(CMAKE_BUILD_TYPE_TOLOWER MATCHES debug OR
-       CMAKE_BUILD_TYPE_TOLOWER MATCHES relwithdebinfo)
+    IF(CMAKE_BUILD_TYPE_TOLOWER MATCHES debug)
         SET(FLAGS "${FLAGS} -DDEBUG")
 
         IF (CMAKE_COMPILER_IS_GNUCXX)
             # Help getting debug info
             SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g -pg")
         ENDIF()
+    ELSEIF(CMAKE_BUILD_TYPE_TOLOWER MATCHES relwithdebinfo)
+        IF (CMAKE_COMPILER_IS_GNUCXX)
+            # Help getting debug info
+            SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -g")
+        ENDIF()
     ENDIF()
 ENDIF()

```

**Comment by akien-mga** [comment]
The patch looks good :)

**Comment by Bertram25** [comment]
@akien-mga I can cherry-pick that to 1.0 afterward, if you want.

**Comment by akien-mga** [comment]
Thanks! For 1.0, if you cherry-pick the fix for RelWithDebInfo, it would be nice to grab http://svnweb.mageia.org/packages/cauldron/valyriatear/current/SOURCES/valyriatear-1.0.0-mga-cmake-luabind.patch?view=markup too and update the luabind embedded version with that of the submodule.

I think most distros ship GCC 5 nowadays so they would all get issues with the older luabind version.

**Comment by Bertram25** [comment]
All done!

Follow the tag:
https://github.com/ValyriaTear/ValyriaTear/releases/tag/1.0.0-gcc5

Cheers,
