### ISSUE TITLE
Language selection broken in Windows

### ISSUE THREAD

**Issue by gunchleoc** [ValyriaTear/ValyriaTear#545]
I tried to select a language other than English, and the game remembers the selection, but does not translate anything. Restarting the game doesn't help.

Version: 1.1.0 Sept 4 2014

Windows 7, 64 bit.

ETA: This is an upstream bug, so I have filed a bug over there as well:

https://bitbucket.org/allacrost/allacrost/issues/51/language-selection-broken-in-windows

**Comment by Bertram25** [comment]
Hey @gunchleoc 
As told in #546 ,

As for your translation issue, if and only if you are on linux, it is true that sometimes the translations don't get updated properly the first time.
After modifying the `LINGUAS` file, you'll need to get rid of your `CMakeCache.txt` file and the `CMakeFiles/` folder and reinvoke CMake again. Then, during the 'make' step, you should see a line looking like: `Generating gd.gmo`

If you are on windows, you'll have to install poedit, open the `gd.po` file with it and save. This will create a `.mo` file next to the `.po` file.
You'll then have to copy this file as `valyriatear.mo` into the folder `<repository_root_folder>\po\gd\LC_MESSAGES`
E.g.: `C:\Users\Me\dev\ValyriaTear\po\gd\LC_MESSAGES\valyriatear.mo`
Then, you should be able to make the language work.

I hope this will help you.

**Comment by gunchleoc** [comment]
I mean I cant select any of the already existing languages other than English at all, never mind adding a new one. Try selecting "Deutsch" on Windows.

**Comment by Bertram25** [comment]
Let me assess a few things:
- Are on Windows?
- Did you clone and compiled ValyriaTear yourself, or is it from an instance used from the Windows installer?

**Comment by Bertram25** [comment]
Ok, so as discussed, this is from installer taken on blogspot, installed on Win7. Interesting ... I'll check on windows myself asap.

**Comment by gunchleoc** [comment]
I had a look at my browser history, I must have downloaded it from SourceForge. `valyriatear-win32-1.0.0-installer.exe`

**Comment by gunchleoc** [comment]
I managed to create a debug build with Visual Studio 2013 on the current git version. The issue is still here, so please reopen.

The vs project didn't generate and of the translation binaries, so I just grabbed them from my Linux build. Translation loading works fine on Linux.

**Comment by Bertram25** [comment]
ok, you're right. While it is feasible to make it work on Windows, it is definitely worth improving.
the thing is we need to add checks the gettext tools are installed in a CMake find module file of some sort first. Then, we can ask windows users to install what's needed at cmake configure time and ensure the translation binaries can be generated automatically.

**Comment by akien-mga** [comment]
You have a module for that: https://cmake.org/cmake/help/v3.0/module/FindGettext.html

**Comment by Bertram25** [comment]
Must say I was pretty sure there was something. ;)

**Comment by gunchleoc** [comment]
FYI this is how it loos with only the German and Gaelic translation files added:
![languages](https://cloud.githubusercontent.com/assets/4095570/24037464/cc848fea-0af5-11e7-8381-9e430fac17d0.png)
So it at least detects the presence of the language catalogs.

BTW I just noticed that the language name for Japanese is in English. I know what the native name is, so I can fix that up.

**Comment by Bertram25** [comment]
> So it at least detects the presence of the language catalogs.

Yup, I added this some times ago for disambiguation purpose.

**Comment by gunchleoc** [comment]
I am now working on this in https://github.com/gunchleoc/ValyriaTear/tree/545-translation-loading-windows - the first step will be a successful compile under MSys2/MinGW, since my Visual Studio license has expired.

**Comment by Bertram25** [comment]
I took my time but ok, duly noted. Feel free to keep me updated on this. I also reviewed your PRs.

**Comment by gunchleoc** [comment]
Since this is now fixed in MSys2 builds, can we close this bug?

**Comment by Bertram25** [comment]
Sure. Nice work.
