### ISSUE TITLE
VisualStudio: Error 1 error LNK2019: unresolved external symbol _SDL_main referenced in function _main

### ISSUE THREAD

**Issue by gunchleoc** [ValyriaTear/ValyriaTear#556]
Compiling with VisualStudio causes a linking error:

~~~~
Error 1 error LNK2019: unresolved external symbol _SDL_main referenced in function _main
~~~~

This happens because `SDL_main.h` contains the line `#define main SDL_main`

- https://forums.libsdl.org/viewtopic.php?p=6759
- https://stackoverflow.com/questions/6847360/error-lnk2019-unresolved-external-symbol-main-referenced-in-function-tmainc

**Comment by Bertram25** [comment]
@gunchleoc Could you try adding:
#undef main
after the #include <SDL.h> when on VisualStudio?

If it works, we may use #ifdefs to do it automatically.
cheers,

**Comment by gunchleoc** [comment]
Tried it, didn't work :(

**Comment by Bertram25** [comment]
And in the second comment, they say it is because main should be declared like this:
int main(int argc, char *argv[])
I believe we just changed that to:
int main(int argc, const char *argv[])
Can you remove the const and see whether it helps?

Cheers,
