### ISSUE TITLE
expr == false or !expr ?

### ISSUE THREAD

**Issue by RyDroid** [ValyriaTear/ValyriaTear#559]
Hi.

In the source code, I saw some `expr == false`, that seems strange to me. I am more used to `!expr`, but it is true that it is less explicit. So I am wondering if it is an intended coding style in this project or not.

Regards.

**Comment by Bertram25** [comment]
Hey,

I'm definitely for using !expr for me, just as a matter of taste and as it is taking less space.
Feel free to use that way.
Cheers,

**Comment by RyDroid** [comment]
Ok. `cd src && $(grep -r ' == false' | wc -l) -eq 0` should be used in Travis CI to check that.

**Comment by RyDroid** [comment]
The same thing should be applied for true. https://github.com/ValyriaTear/ValyriaTear/pull/562
