### ISSUE TITLE
Running with cancel key is not intuitive

### ISSUE THREAD

**Issue by gunchleoc** [ValyriaTear/ValyriaTear#570]
When I want to run on the map, I keep pressing the action key (F) and get caught before I remember that I have to use the cancel key (D).

**Comment by Bertram25** [comment]
Running using the cancel key permits to avoid adding a key for this and is especially handy when playing using a pad. Sorry, but I won't change this without a good counter proposal.

**Comment by gunchleoc** [comment]
Why not use F like I suggested? No key added at all.

If it's better for a pd, would it be complicated to keep it like it is for the pad and change it for the keyboard? Although that might be confusing as well.

**Comment by Bertram25** [comment]
F (or the confirm key) is used atm to trigger a battle before the enemy does it. The goal is that if the character face the enemy and is first to select the battle, the party gets a small advantage.
Thus, F is already used, even if not actually introduced to the player yet.

**Comment by gunchleoc** [comment]
Ah, I didn't know that. OK, let's scrap this idea then.
