### ISSUE TITLE
update-copyright.sh has no license

### ISSUE THREAD

**Issue by RyDroid** [ValyriaTear/ValyriaTear#600]
Hi.

`update-copyright.sh` has no license. It comes from Warmux, a dead project.
https://github.com/yeKcim/warmux
https://linuxfr.org/news/warmux-cd-remix#comment-1648747

My contribution can be considered to be under Creative Commons 0 (version 1.0). But I am not the only contributor of this file. Has someone more information?

Regards.

**Comment by Bertram25** [comment]
Hmm, you're right. This file is muddy. Let's remove it. Copyright years update is not mandatory anyway. Especially on files without major modifications.
