### ISSUE TITLE
Kalya actually calls Herth "father"

### ISSUE THREAD

**Issue by eugeneloza** [ValyriaTear/ValyriaTear#602]
> #: ../data/story/layna_village/layna_village_center_script.lua:478
> msgid "Father!"
> msgstr "Father!"
> 
> #: ../data/story/layna_village/layna_village_center_script.lua:488
> msgid "Father! Orlinn has disappeared. I saw him taking the forest pathway!"
> msgstr "Father! Orlinn has disappeared. I saw him taking the forest pathway!"
> 
> #: ../data/story/layna_village/layna_village_center_script.lua:520
> msgid "But father!"
> msgstr "But father!"

Which actually contradicts to

> #: ../data/story/layna_village/layna_village_kalya_house_script.lua:307
> msgid ""
> "Wait! There is one more thing. Why are you calling your own father by his "
> "actual name?"
> msgstr "Wait! There is one more thing. Why are you calling your own father by his actual name?"
> 
> #: ../data/story/layna_village/layna_village_kalya_house_script.lua:309
> msgid "That's because he's not our father."
> msgstr "That's because he's not our father."

Not that it's critical, but might be worth fixing :)

**Comment by Bertram25** [comment]
Good catch! :)
Since this scene will stay for 1.1, I'll fix it while working on the game start.
Many thanks for the report.
