### ISSUE TITLE
Battle victory doesn't level up the character properly.

### ISSUE THREAD

**Issue by flaviojs** [ValyriaTear/ValyriaTear#612]
Battle victory gradually adds XP to the character in:
https://github.com/ValyriaTear/ValyriaTear/blob/682e19366668f57f47066ddbd0b73db9b0c801ee/src/modes/battle/finish/battle_victory.cpp#L380

The actual level up happens in:
https://github.com/ValyriaTear/ValyriaTear/blob/682e19366668f57f47066ddbd0b73db9b0c801ee/src/common/global/actors/global_character.cpp#L633

### Problem 1:
When you level up, the variable `GlobalCharacter:: _experience_for_next_level` is not updated to the next value.
This means that the other calls to `GlobalCharacter::AddExperiencePoints` (while gradually adding XP) will level up the character yet again.

### Problem 2:
If `GlobalCharacter::AddExperiencePoints` receives enough experience to level up multiple times, it will only level up once.

**Comment by Bertram25** [comment]
oops, will have a look while rebalancing. Thanks!

**Comment by Bertram25** [comment]
Fixed! Thanks again for the nice catch.
