### ISSUE TITLE
Error : failed to change directory to data location

### ISSUE THREAD

**Issue by B4rabbas** [ValyriaTear/ValyriaTear#616]
Hello,
when 'im trying to lauche the game I've this message :

barabbas@barabbas-H:~$ '/home/barabbas/ValyriaTear/src/valyriatear'
ERROR:/home/barabbas/valiriatear/ValyriaTear/src/main.cpp:main:533: 
EXCEPTION:/home/barabbas/valiriatear/ValyriaTear/src/main.cpp:main:508: ERROR: failed to change directory to data location

**Comment by akien-mga** [comment]
Looks like you changed the location of your build (and data) folder after compilation, removing the "valiriatear" intermediary folder. I don't remember how VT locates data when ran from source butbyou likely need to recompile to fix the path.

**Comment by B4rabbas** [comment]
Yep many thanks. :)

**Comment by Bertram25** [comment]
@B4rabbas  I confirm you need to rebuild to make it work. Have fun with the code even though I still believe I've got some work left to give people a smooth experience with master.

@akien-mga Thanks for the watch :)

**Comment by B4rabbas** [comment]
Cheers bro

**Comment by akien-mga** [comment]
@Bertram25 I'm always around, waiting for you to start playing with @godotengine to code with you some more again :D

**Comment by Bertram25** [comment]
@akien-mga would be cool. :) Whenever I have a more streamlined dev pipeline for VT, I'd like to try godot for some crazy ideas and fix a few things for OD also. Cheers,
