### ISSUE TITLE
Error with key recognition in Key Settings menu

### ISSUE THREAD

**Issue by gunchleoc** [ValyriaTear/ValyriaTear#618]
To reproduce:

1. Enter the Key Settings menu
2. Chose "Confirm" and Hit "F" to select
3. Hit "Return" key to change code to return key
4. Hit "Return" key to select "Confirm" again
5. Hit "F" again to switch the key back to F. A non-existent key is chosen.

![valyriatear_assign_key](https://user-images.githubusercontent.com/4095570/46570939-5bde2d80-c964-11e8-98c4-07153b158788.png)

The key recognized instead of 102 F is 21968 嗐 or 21982 嗞 etc... looks like the memory is already overwritten.

Tested on Ubuntu 18.04 with German keyboard layout.

**Comment by Bertram25** [comment]
ok good point. Is this the reason you forbid enter as a key in your PR?

**Comment by gunchleoc** [comment]
I do not see where I forbid the enter key here - the enter key is not used. This is a branch directly off master, so it has nothing to do with the other branch where I added support for the enter key ;)

**Comment by Bertram25** [comment]
Ah get it now.
