### ISSUE TITLE
Battles - Status effects icons should first be bigger with all the work related.

### ISSUE THREAD

**Issue by Bertram25** [ValyriaTear/ValyriaTear#634]
status effects applied on characters should be bigger so that they can be read much more easily.
This is some work and means also breaking a few other menus.

**Comment by eugeneloza** [comment]
I'm not really sure if the status icons should be larger. They were quiet readable the last time I've played Valyria Tear (but that was long ago :)). Maybe, playing a bit with colors might be useful, but not something that requires a lot of work with no clear gain.
