### ISSUE TITLE
Please update translations on Transifex

### ISSUE THREAD

**Issue by gunchleoc** [ValyriaTear/ValyriaTear#638]
The translation files on Transifex are too old, could you please push a current .pot file?

See https://forum.freegamedev.net/viewtopic.php?p=78129#p78129

**Comment by Bertram25** [comment]
Hey, :)

I will do so tonight.



<div>-------- Message d'origine --------</div><div>De : gunchleoc <notifications@github.com> </div><div>Date :25/02/2019  19:57  (GMT+01:00) </div><div>À : ValyriaTear/ValyriaTear <ValyriaTear@noreply.github.com> </div><div>Cc : Subscribed <subscribed@noreply.github.com> </div><div>Objet : [ValyriaTear/ValyriaTear] Please update translations on Transifex
  (#638) </div><div>
</div>The translation files on Transifex are too old, could you please push a current .pot file?

See https://forum.freegamedev.net/viewtopic.php?p=78129#p78129

**Comment by Bertram25** [comment]
Was done in: 730120c52771104742631aaa6c189bb77d3fa7b4
and on transifex.

Cheers,

**Comment by gunchleoc** [comment]
Thanks!
