### ISSUE TITLE
Test truncation and overlaps

### ISSUE THREAD

**Issue by gunchleoc** [ValyriaTear/ValyriaTear#645]
I have some text truncation and overlap issues with Scottish Gaelic that I cannot resolve by shortening the translations further.

Battle lost screen - "OK" and "Cancel":

![Battle Lost](https://user-images.githubusercontent.com/4095570/64919774-c9b2ec00-d7a6-11e9-8c6b-078c47bfc95e.png)

Skills tree, description on the bottom for multiple skills (the number 11 is truncated here, and it would be even worse for magical attack) - using vertical alignment should solve this:

![Skills Tree](https://user-images.githubusercontent.com/4095570/64919781-cfa8cd00-d7a6-11e9-9f07-4655e53d2cb4.png)

And in the end credits, screen for the Allacrost Artwork Team:

![Allacrost Artwork Team](https://user-images.githubusercontent.com/4095570/64919795-e51df700-d7a6-11e9-8906-bc2964c7313a.png)

**Comment by Bertram25** [comment]
@gunchleoc Just saw that one. I'll check what I can do.

**Comment by Bertram25** [comment]
@gunchleoc For the skills, here is the best I can achieve without too much refactoring:
![image](https://user-images.githubusercontent.com/765917/65186609-43c6c780-da6a-11e9-91f0-a1efc06dfc23.png)

**Comment by gunchleoc** [comment]
Tested and looking good, thanks a lot!
