### ISSUE TITLE
Please make a tarball with submodules included

### ISSUE THREAD

**Issue by ibara** [ValyriaTear/ValyriaTear#648]
This will make packaging ValyriaTear much easier for us porters/packagers.

**Comment by Bertram25** [comment]
I was sure this one was coming ;)

Actually, I'd like to have a script of even CI for that. But will do.

**Comment by Bertram25** [comment]
@ibara Let's have a try. Can you tell me if this is usable for you?
https://github.com/ValyriaTear/ValyriaTear/releases/download/1.1.0/ValyriaTear-src-with-deps-1.1.0.tar.gz

**Comment by akien-mga** [comment]
@Bertram25 That works, but for future tarballs, it would be good to have a more explicit folder name than just "ValyriaTear". Source tarballs typically use the same folder name as the tarball name itself, e.g. `ValyriaTear-1.1.0.tar.xz` containing a `ValyriaTear-1.1.0` folder (that's what GitHub's autogenerated tarballs would give, and what most packaging systems will expect - `$name-$version`).

Once unarchived and the tarball deleted, you no longer know what actual version it is that you have if the folder is just "ValyriaTear".

**Comment by ibara** [comment]
This is fine with me (the OpenBSD ports tree doesn't have the concern that @akien-mga mentions, though it is true for people downloading for self-compilation).

**Comment by Bertram25** [comment]
> Once unarchived and the tarball deleted, you no longer know what actual version it is that you have if the folder is just "ValyriaTear".

Duly noted. For next release, I'll definitely make some script for that.
