### ISSUE TITLE
Some issues in german translation?

### ISSUE THREAD

**Issue by cyberpunkbln** [ValyriaTear/ValyriaTear#656]
Hello,

in the newest version some german translations are in english, where are translated in german in earlier versions?

thx

**Comment by gunchleoc** [comment]
If you want to help, translations are here: https://www.transifex.com/valyria-tear/valyria-tear/language/de/

**Comment by Sturwandan** [comment]
The link you provided is 404 not found. However I fixed the URL to https://www.transifex.com/valyria-tear/valyria-tear and it worked. 

Anyway, I don't get how to translate strings. I have tried to log in but even after logging in I don't see how to get to actual line I can try to translate (though I'm not German, so I have poked other language, which isn't 100% translated)

**Comment by eugeneloza** [comment]
@Sturwandan Select language - select file - and then you have two ways to translate: download the `po` file and use `PoEdit` - available both on Windows and Linux. Or press big blue "Translate" button to start translating online - much better if you are working with several people in parallel, as you don't create merge conflict with different po files, but less convenient IMHO. See the video where to get those:

https://user-images.githubusercontent.com/10726162/112715311-1b821980-8ee8-11eb-8586-dd88a746ec9f.mp4

**Comment by Bertram25** [comment]
Hey @eugeneloza long time no see ;)

@Sturwandan if you're still interested, I can activate Russian if you want.
