### ISSUE TITLE
luabind and vt-utils are not included in release tarball

### ISSUE THREAD

**Issue by Sturwandan** [ValyriaTear/ValyriaTear#659]
I have tried to install the game from source. Upon trying it, I have found out that release file downloaded from github (1.1.0.tar.gz) does not have luabind and vt-utils which has to be cloned separately. This is a problem because git submodules won't work on release tarball since it has git metadata stripped.

I was able to download those two libraries manually but removing empty directories luabind and utils from src/ and using git clone --depth=3 then renaming vt-utils to utils, but in my opinion, the release tarball has to include all self-hosted dependencies.

**Comment by Sturwandan** [comment]
Though it didn't build anyway, so I had to use the git master instead. The git master did build on my system (Slackware64 15.0)

**Comment by Sturwandan** [comment]
I was able to complete the game (current master from github), however, I didn't get the chest in the cave with cuneiform inscription, it's enclosed by chasms from both sides. 
In my walkthrough I have got hiccups which happened because I didn't remember the game from when I played it last time, well enough. It turns out that fighting fenrir when he has Orlinn was irreversible because the night time starts and I wasn't able to spend ingredients I collected to get the prismatic ring, since the return in nighttime triggers the event. The other hiccup was because I didn't know there was the upper limit of 20 levels, otherwise I would have tried to conserve some XP, so I could have gotten more improvements after I got ores. Though the enemies were no match for my team anyway, with Kalya spamming fire spells while hav
I have noticed some problems with text here and there, since I have non-default keyboard controls (WASD + L;'<enter>). Some texts have suggestions changed to tell the current key and some mention the key used in original control layout. Also the plaque near the entrance of first cave says "PM" in place of "SP"

**Comment by Bertram25** [comment]
Hey @Sturwandan ,

Sorry for being slow here, I was quite busy.
The default package from github is indeed a per repository file, which means that indeed the submodules aren't there.
It's a good point, and I'll try to make sure a reference source file is provided for the next release.

**Comment by Bertram25** [comment]
> In my walkthrough I have got hiccups which happened because I didn't remember the game from when I played it last time, well enough. It turns out that fighting fenrir when he has Orlinn was irreversible because the night time starts and I wasn't able to spend ingredients I collected to get the prismatic ring, since the return in nighttime triggers the event.

intended, as a advanced fomo thing ;)
The item will be back, but it was more some kind of reward for the most focused players.

> . The other hiccup was because I didn't know there was the upper limit of 20 levels, otherwise I would have tried to conserve some XP, so I could have gotten more improvements after I got ores. Though the enemies were no match for my team anyway, with Kalya spamming fire spells while having loads of SP to spare.

Well, I bet it's a non issue then. But it should help when I lighten the cap after adding the next few maps. Not there yet, though.

> I have noticed some problems with text here and there, since I have non-default keyboard controls (WASD + L;'). Some texts have suggestions changed to tell the current key and some mention the key used in original control layout. Also the plaque near the entrance of first cave says "PM" in place of "SP".

Ok, I will check that last one when I can. Nice catch.

> I'm not sure if this is a bug or not, but when I move the mushrooms in this position, the ball get stuck, even though visually it seems that it should roll through. I have found a different configuration of mushrooms, which worked though.

Hmm, I bet the joy of "physics" (note the quotes as I agree it's really basic) based puzzles. I'll keep it in mind but fixing it is tedious as I'd need to add some kind of margin and/or gridding to the physics and that may add yet other issues instead.

Thanks for the playthrough and for the feedback :)

**Comment by Sturwandan** [comment]
Thank you for answer.

Mainly, the problem is that 20 levels is an arbitrary limit, which you have no idea about until you hit it, and when you do, you can't do anything with it. I have expected, that by killing enough enemies and collecting enough ores, I can fill the skill trees completely for both characters.

About the inaccessible chest, is it supposed to be a puzzle which I didn't solve or it's there just to tease the player?

**Comment by Bertram25** [comment]
Added https://github.com/ValyriaTear/ValyriaTear/releases/download/1.1.0/ValyriaTear-src-with-deps-1.1.0.tar.gz before I forget I did this.
Will check the other smaller issue whenever I can.

**Comment by Bertram25** [comment]
Well, I looked for the PM/SP thing and couldn't find it, I'll have a playthrough once reaching a bit further and I'll fix that along the way. Closing this one as the other issue is fixed.
